<<<<<<< HEAD
<<<<<<< Updated upstream
<<<<<<< Updated upstream
blank_issues_enabled: false
=======
blank_issues_enabled: true
>>>>>>> Stashed changes
=======
blank_issues_enabled: true
>>>>>>> Stashed changes
=======
blank_issues_enabled: false
>>>>>>> origin/feat/go-port-and-ui-improvements-13710034216498711139
contact_links:
  - name: Question / Help
    url: https://github.com/diegosouzapw/OmniRoute/discussions
    about: For questions or help with setup, please use GitHub Discussions instead of opening an issue.
